using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Arcanica.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class RoadmapWindow : DefaultWindow
{
    public RoadmapWindow()
    {
        RobustXamlLoader.Load(this);
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow("[font size=24]Arcanica Roadmap[/font]");
        Header.SetMessage(msg);
    }
}
