using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Arcanica.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class RoadmapHeader : BoxContainer
{
    public string? Text
    {
        get => TextValue.Text;
        set => TextValue.Text = value;
    }

    public RoadmapHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
